### ISSUE TITLE
Repeteables with image or file fields not working

### ISSUE THREAD

**Issue by oterox** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#18]
Repeteables with image or file fields doesn't work.
If you set wp_debug to true you can see more info:

for images:

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/lab01/wp-content/themes/twentyeleven_test/metaboxes/meta_box.php on line 245

and for file fields:

Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/lab01/wp-content/themes/twentyeleven_test/metaboxes/meta_box.php on line 245 

Notice: Undefined variable: post in /var/www/lab01/wp-content/themes/twentyeleven_test/metaboxes/meta_box.php on line 219 
Notice: Trying to get property of non-object in /var/www/lab01/wp-content/themes/twentyeleven_test/metaboxes/meta_box.php on line 219 

I'm using 2 repeatables, 1 for images and another one for files(pdf docs).
![image](https://f.cloud.github.com/assets/1680006/62279/8d51dad2-5cf6-11e2-873d-a38243895e41.png)

**Comment by tammyhart** [comment]
I can't seem to duplicate this error. Can you paste in your $fields array?

**Comment by oterox** [comment]
is it wordpress 3.5, using the twentyeleven theme for testing.

<pre>
    array( 
        'label' => 'Gallery images', 
        'desc'  => 'A description for the field.', 
        'id'    => $prefix.'repeatable_image', 
        'type'  => 'repeatable', 
        'repeatable_fields' => array ( 
            'gallery' => array(
                'label' => 'Image',
                'id' => 'gallery',
                'type' => 'image'
            )
        )
    ),
    array( 
        'label' => 'Documents', 
        'desc'  => 'A description for the field.', 
        'id'    => $prefix.'repeatable_file', 
        'type'  => 'repeatable',
        'repeatable_fields' => array ( 
            'documents' => array(
                'label' => 'doc',
                'id' => 'document',
                'type' => 'file'
            )
        )
    )
</pre>

**Comment by kellygrape** [comment]
Try to alter your code to not use the initial 'gallery' or 'documents' before your array.

For example ---

```
array( 
    'label' => 'Gallery images', 
    'desc'  => 'A description for the field.', 
    'id'    => $prefix.'repeatable_image', 
    'type'  => 'repeatable', 
    'repeatable_fields' => array ( 
        array(
            'label' => 'Image',
            'id' => 'gallery',
            'type' => 'image'
        )

    )
),
```

**Comment by oterox** [comment]
Kelly, that doesn't work neither.
I'm using latest version with new metabox but i still can add a repeteable with images and another repeteable for files.
1 repeatable works perfect, but 2 doesn't.

**Comment by tammyhart** [comment]
I fixed a couple bugs in recent commits that I think will help with this. Please update and let me know.

**Comment by oterox** [comment]
still doesn't work.

With this version i can't even add an image.There's a js error in scripts.js line 10:

![metaboxes_Error](https://f.cloud.github.com/assets/1680006/135566/cee76f74-7129-11e2-8b86-fc6188f0179c.jpg)

for testing latest metaboxes version i've added metaboxes code to twentyTwelve theme, WP 3.5.1, no plugins:

<pre>
    array( 
        'label' => 'Gallery images', 
        'desc'  => 'A description for the field.', 
        'id'    => $prefix.'repeatable_image', 
        'type'  => 'repeatable', 
        'repeatable_fields' => array ( 
            'gallery' => array(
                'label' => 'Image',
                'id' => 'gallery',
                'type' => 'image'
            )
        )
    ),
    array( 
        'label' => 'Documents', 
        'desc'  => 'A description for the field.', 
        'id'    => $prefix.'repeatable_file', 
        'type'  => 'repeatable',
        'repeatable_fields' => array ( 
            'documents' => array(
                'label' => 'doc',
                'id' => 'document',
                'type' => 'file'
            )
        )
    )
</pre>

**Comment by tammyhart** [comment]
My mistake; I didn't define "event" correctly. Strange that it was still working for me though. I've updated scripts.js. Try it now.

**Comment by oterox** [comment]
now i can't add any image.The media upload window opens but when i upload an image and add it to the post, the image is not there

**Comment by tammyhart** [comment]
You're right, I was missing a couple of divs from the image and file fields. This comes from working on this version and the version for a client project and it had me confused. Try updated meta_box.php and try again.

**Comment by oterox** [comment]
the images works again but only the first one.When you click to add a second one the second image gets populated with the previous image and dont works.Which theme are you using to test it? a custom theme? try with wp default one.
Thk you for trying to solve the problem Tammy :)

**Comment by EWSEL** [comment]
I have the same problem it not work for me i get the error

> Warning: array_key_exists() expects parameter 2 to be array, null given in /home/++++++/public_html/++++/ > wp-content/themes/+++++/src/meta_box.php on line 251

**Comment by hugoassuncao** [comment]
I'm having the same problem: it works only for the first image.

**Comment by krembo99** [comment]
I can confirm to reproduce this problem. All image features (upload, remove) works only for first image.

**Comment by iamsalmanafzal** [comment]
Hello Sir, if any one can reply me fast - i will be very thankful.

When i upload image and update post or page. i will get numeric value of image in custom fields. like "35" , "41", "134" but i think it should show URL of Image. insteaded of Numeric value. 

It would be great if anyone can reply me today.

**Comment by tarex** [comment]
@tammyhart hi can you please check your scripts.js file . i've done some changes and its working fine with me . 

this one should work . 

```
jQuery(function($) {

    // the upload image button, saves the id and outputs a preview of the image
    var imageFrame;
    $('.meta_box_upload_image_button').live('click',function(e) {
        e.preventDefault();

        var options, attachment;

        $self = $(event.target);
        $div = $self.closest('div.meta_box_image');

        // if the frame already exists, open it
        if ( imageFrame ) {
            imageFrame.open();
            return;
        }

        // set our settings
        imageFrame = wp.media({
            title: 'Choose Image',
            multiple: false,
            library: {
                type: 'image'
            },
            button: {
                text: 'Use This Image'
            }
        });

        // set up our select handler
        imageFrame.on( 'select', function() {
            selection = imageFrame.state().get('selection');

            if ( ! selection )
            return;

            // loop through the selected files
            selection.each( function( attachment ) {
                console.log(attachment);
                var src = attachment.attributes.sizes.full.url;
                var id = attachment.id;

                $div.find('.meta_box_preview_image').attr('src', src);
                $div.find('.meta_box_upload_image').val(id);
            } );
        });

        // open the frame
        imageFrame.open();
    });









    // the remove image link, removes the image id from the hidden field and replaces the image preview
    $('.meta_box_clear_image_button').live('click',function(e) {
          e.preventDefault();
        var defaultImage = $(this).parent().siblings('.meta_box_default_image').text();
        $(this).parent().siblings('.meta_box_upload_image').val('');
        $(this).parent().siblings('.meta_box_preview_image').attr('src', defaultImage);
        //return false;
    });

    // the file image button, saves the id and outputs the file name
    var fileFrame;
    $('.meta_box_upload_file_button').click(function(e) {
        e.preventDefault();

        var options, attachment;

        $self = $(event.target);
        $div = $self.closest('div.meta_box_file_stuff');

        // if the frame already exists, open it
        if ( fileFrame ) {
            fileFrame.open();
            return;
        }

        // set our settings
        fileFrame = wp.media({
            title: 'Choose File',
            multiple: false,
            library: {
                type: 'file'
            },
            button: {
                text: 'Use This File'
            }
        });

        // set up our select handler
        fileFrame.on( 'select', function() {
            selection = fileFrame.state().get('selection');

            if ( ! selection )
            return;

            // loop through the selected files
            selection.each( function( attachment ) {
                console.log(attachment);
                var src = attachment.attributes.url;
                var id = attachment.id;

                $div.find('.meta_box_filename').text(src);
                $div.find('.meta_box_upload_file').val(src);
                $div.find('.meta_box_file').addClass('checked');
            } );
        });

        // open the frame
        fileFrame.open();
    });

    // the remove image link, removes the image id from the hidden field and replaces the image preview
    $('.meta_box_clear_file_button').click(function() {
        $(this).parent().siblings('.meta_box_upload_file').val('');
        $(this).parent().siblings('.meta_box_filename').text('');
        $(this).parent().siblings('.meta_box_file').removeClass('checked');
        return false;
    });

    // function to create an array of input values
    function ids(inputs) {
        var a = [];
        for (var i = 0; i < inputs.length; i++) {
            a.push(inputs[i].val);
        }
        //$("span").text(a.join(" "));
    }






    // // repeatable fields
    $('a.meta_box_repeatable_add').on('click', function(e) {

        e.preventDefault();
        console.log('clicked');
        // clone
        var row = $('table.meta_box_repeatable').find('tbody tr:last-child');
        var clone = row.clone();

        //var defaultImage = clone.closest('.meta_box_default_image').text();
        //console.log(defaultImage);
        console.log(clone);

        clone.find('.meta_box_upload_image').val('');
        clone.find('.meta_box_preview_image').attr('src',' ');

        clone.find('select.chosen').removeAttr('style', '').removeAttr('id', '').removeClass('chzn-done').data('chosen', null).next().remove();
        clone.find('input.regular-text, textarea, select').val('');
        clone.find('input[type=checkbox], input[type=radio]').attr('checked', false);
        row.after(clone);





        // increment name and id
        clone.find('input, textarea, select')
            .attr('name', function(index, name) {
                return name.replace(/(\d+)/, function(fullMatch, n) {
                    return Number(n) + 1;
                });
            });
        var arr = [];
        $('input.repeatable_id:text').each(function(){ arr.push($(this).val()); }); 
        clone.find('input.repeatable_id')
            .val(Number(Math.max.apply( Math, arr )) + 1);
        if (!!$.prototype.chosen) {
            clone.find('select.chosen')
                .chosen({allow_single_deselect: true});
        }
        //
        //return false;
    });





    $('a.meta_box_repeatable_remove').live('click', function(e){
        e.preventDefault();
        console.log('removed');
        $(this).closest('tr').remove();
        //return false;
    });








    $('.meta_box_repeatable tbody').sortable({
        opacity: 0.6,
        revert: true,
        cursor: 'move',
        handle: '.hndle'
    });




    // // post_drop_sort    
    $('.sort_list').sortable({
        connectWith: '.sort_list',
        opacity: 0.6,
        revert: true,
        cursor: 'move',
        cancel: '.post_drop_sort_area_name',
        items: 'li:not(.post_drop_sort_area_name)',
        update: function(event, ui) {
            var result = $(this).sortable('toArray');
            var thisID = $(this).attr('id');
            $('.store-' + thisID).val(result) 
        }
    });

    $('.sort_list').disableSelection();

    // turn select boxes into something magical
    if (!!$.prototype.chosen)
        $('.chosen').chosen({ allow_single_deselect: true });
});
```

**Comment by tarex** [comment]
@iamsalmanafzal  use `wp_get_attachment_image_src( $attachment_id, $size, $icon );`

**Comment by sethta** [comment]
@oterox I found that the issue was for Firefox only, but it worked in Chrome. The above script by @tarex almost works without flaw; you just need to change `javascript$self = $(event.target);` to `javascript$self = $(e.target);` on lines 10 and 77.

**Comment by everlast000** [comment]
Hi, guys!

I'm kind of having the same problem, and tarex' code doesn't work. The thing is:

I have a repeatable field with Text input and Image. Whenever I first choose an image and input a text, it works fine.

But then I click the add new repeatable button, and the image gets cloned from the first one. Whenever I want to Delete the image or click the "Choose image" button, it doesn't do anything and my screen scrolls to the top. 

If I click save, and then click the delete or choose image button, everything works. It just doesn't work after you hit the "new repeatable field".

**Comment by tarex** [comment]
hi, @everlast000  i'm not using this script now . you can check this one 
https://github.com/Gizburdt/Wordpress-Cuztom-Helper/

**Comment by everlast000** [comment]
Hi @tarex wow, that looks complicted :p I'll have a try to implement this.

Edit: It seems it cannot repeat the image field?

**Comment by panarican** [comment]
I fixed the repeatable bug (it was a javascript bug) on my repo. You can download it here:

https://github.com/panarican/wordpress-boilerplate

I also added some helper template functions and fixed/added a few more things. I'm planning on adding field validation in the near future.

https://github.com/panarican/wordpress-boilerplate/blob/master/inc/helper/template.php

**Comment by bajun** [comment]
Hello guys!
Anybody can help with "array_key_exists() expects parameter 2 to be array" bug?

**Comment by panarican** [comment]
http://php.net/manual/en/function.array-key-exists.php
